#!/bin/bash

if [ -z "$SAFE_ADDR" ]; then
    echo ' must set SAFE_ADDR env '
    exit 1
fi

# Thoughts to re-org this code
# BearerRef check for method name
# Arity check for method name

postInstance() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance,?Image,?AuthID
    curl -XPOST $SAFE_ADDR/postInstance -d "{\"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

postInstanceLocal() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance,?Image
    curl -XPOST $SAFE_ADDR/postInstanceLocal -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostInstance() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID
    curl -s -w "postInstance %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delInstanceLocal() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}


delInstance() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

        
postVMInstance() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Vpc,?AuthID,?Cidr
#
# ?Instance, ?Image, ?Vpc, ?NetAddr, ?Cidr
    echo curl -XPOST $SAFE_ADDR/postVMInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
    curl -XPOST $SAFE_ADDR/postVMInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

postVMInstanceLocal() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Vpc
    curl -XPOST $SAFE_ADDR/postVMInstanceLocal -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVMInstance() {
    local principal=$1
    shift 1
# ?Instance,?Image,?AuthID,?Cidr,?Vpc,?TrustHub
#
# [qiang] Make a rest call with 4 params
# ?Instance,?Image,?Vpc,?NetAddr
    curl -s -w "postVMInstance %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVMInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",c\"${2}\",\"${3}\",\"${4}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVMInstance() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVMInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"], \"auth\": \"${AUTH:-1}\"}"
}
 
delVMInstanceLocal() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVMInstance -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}
       
postVpcConfig1() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1
    curl -XPOST $SAFE_ADDR/postVpcConfig1 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVpcConfig1() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1
    curl -s -w "postVpcConfig1 %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVpcConfig1 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVpcConfig1() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig1 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}
        
postVpcConfig2() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2
    curl -XPOST $SAFE_ADDR/postVpcConfig2 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVpcConfig2() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2
    curl -s -w "postVpcConfig2 %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVpcConfig2 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVpcConfig2() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig2 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\": \"${AUTH:-1}\"}"
}
        
postVpcConfig3() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3
    curl -XPOST $SAFE_ADDR/postVpcConfig3 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVpcConfig3() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3
    curl -s -w "postVpcConfig3 %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVpcConfig3 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVpcConfig3() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig3 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\"], \"auth\": \"${AUTH:-1}\"}"
}
        
postVpcConfig4() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4
    curl -XPOST $SAFE_ADDR/postVpcConfig4 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVpcConfig4() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4
    curl -s -w "postVpcConfig4 %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVpcConfig4 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVpcConfig4() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig4 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\"], \"auth\": \"${AUTH:-1}\"}"
}
        
postVpcConfig5() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4,?Config5,?Value5
    curl -XPOST $SAFE_ADDR/postVpcConfig5 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostVpcConfig5() {
    local principal=$1
    shift 1
# ?Vpc,?Config1,?Value1,?Config2,?Value2,?Config3,?Value3,?Config4,?Value4,?Config5,?Value5
    curl -s -w "postVpcConfig5 %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postVpcConfig5 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"], \"auth\":\"${AUTH:-1}\"}"
}

delVpcConfig5() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delVpcConfig5 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\",\"${6}\",\"${7}\",\"${8}\",\"${9}\",\"${10}\",\"${11}\"], \"auth\": \"${AUTH:-1}\"}"
}
        
postInstanceConfigList() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1
    curl -XPOST $SAFE_ADDR/postInstanceConfigList -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostInstanceConfigList() {
    local principal=$1
    shift 1
# ?Instance,?Config1,?Value1
    curl -s -w "postInstanceConfigList %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postInstanceConfigList -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delInstanceConfigList() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConfigList -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postEndorsementLink() {
    local principal=$1
    shift 1
# ?Endorser,?Target
    curl -XPOST $SAFE_ADDR/postEndorsementLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostEndorsementLink() {
    local principal=$1
    shift 1
# ?Endorser,?Target
    curl -s -w "postEndorsementLink %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postEndorsementLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

delEndorsementLink() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delEndorsementLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\": \"${AUTH:-1}\"}"
}
   
postTrustedEndorser() {
    local principal=$1
    shift 1
# ?Endorser,?Target
    curl -XPOST $SAFE_ADDR/postTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

postAndDLinkTrustedEndorser() {
    local principal=$1
    shift 1
# ?Endorser,?Target,?EndorsementLabel
    curl -XPOST $SAFE_ADDR/postAndDLinkTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\", \"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostTrustedEndorser() {
    local principal=$1
    shift 1
# ?Endorser,?Target
    curl -s -w "postTrustedEndorser %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

delTrustedEndorser() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -s -w "postEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postInstanceEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postInstanceEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostInstanceEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?Value
    curl -s -w "postInstanceEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postInstanceEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delInstanceEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -s -w "postConditionalEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

delConditionalEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\": \"${AUTH:-1}\"}"
}

postInstanceConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -XPOST $SAFE_ADDR/postInstanceConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostInstanceConditionalEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Key,?Expected,?Prop,?Value
    curl -s -w "postInstanceConditionalEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postInstanceConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\":\"${AUTH:-1}\"}"
}

delInstanceConditionalEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceConditionalEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\",\"${5}\"], \"auth\": \"${AUTH:-1}\"}"
}

postParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -XPOST $SAFE_ADDR/postParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -s -w "postParameterizedEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delParameterizedEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postInstanceParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -XPOST $SAFE_ADDR/postInstanceParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostInstanceParameterizedEndorsement() {
    local principal=$1
    shift 1
# ?Target,?Prop,?ConfName
    curl -s -w "postInstanceParameterizedEndorsement %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postInstanceParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delInstanceParameterizedEndorsement() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delInstanceParameterizedEndorsement -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postCluster() {
    local principal=$1
    shift 1
# ?Cluster,?OwnerGuard,?JoinerGuard
    curl -XPOST $SAFE_ADDR/postCluster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostCluster() {
    local principal=$1
    shift 1
# ?Cluster,?OwnerGuard,?JoinerGuard
    curl -s -w "postCluster %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postCluster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delCluster() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delCluster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postMembership() {
    local principal=$1
    shift 1
# ?Cluster,?WorkerID
    curl -XPOST $SAFE_ADDR/postMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostMembership() {
    local principal=$1
    shift 1
# ?Cluster,?WorkerID
    curl -s -w "postMembership %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

delMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postAckMembership() {
    local principal=$1
    shift 1
# ?Cluster,?MasterID
    curl -XPOST $SAFE_ADDR/postAckMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostAckMembership() {
    local principal=$1
    shift 1
# ?Cluster,?MasterID
    curl -s -w "postAckMembership %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postAckMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

delAckMembership() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delAckMembership -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postGroupAdmissionPolicy() {
    local principal=$1
    shift 1
# GroupID, PolicyID, TrustedEndorser                                                                                                                    
    curl -XPOST $SAFE_ADDR/postGroupAdmissionPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}
        
postParameterizedConnection() {
    local principal=$1
    shift 1
# ?Target,?Service,?ConfName
    curl -XPOST $SAFE_ADDR/postParameterizedConnection -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostParameterizedConnection() {
    local principal=$1
    shift 1
# ?Target,?Service,?ConfName
    curl -s -w "postParameterizedConnection %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postParameterizedConnection -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

delParameterizedConnection() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delParameterizedConnection -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\": \"${AUTH:-1}\"}"
}

postTrustHubLink() {
    local principal=$1
    shift 1
# ?OtherHub
    curl -XPOST $SAFE_ADDR/postTrustHubLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measurePostTrustHubLink() {
    local principal=$1
    shift 1
# ?OtherHub
    curl -s -w "postTrustHubLink %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/postTrustHubLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

delTrustHubLink() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/delTrustHubLink -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\": \"${AUTH:-1}\"}"
}

postPodPolicy() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/postPodPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postImagePolicy() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/postImagePolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postRequiredPolicy() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/postRequiredPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postQualifierPolicy() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/postQualifierPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

postProhibitedPolicy() {
    local principal=$1
    shift 1
    curl -XPOST $SAFE_ADDR/postProhibitedPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\": \"${AUTH:-1}\"}"
}

checkContainerIsolation() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkContainerIsolation -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckContainerIsolation() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkContainerIsolation %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkContainerIsolation -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkSafeSpark() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkSafeSpark -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckSafeSpark() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkSafeSpark %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkSafeSpark -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkK8sHDFSAccess() {
    local principal=$1
    shift 1
# ?Instance,?File
    curl -XPOST $SAFE_ADDR/checkK8sHDFSAccess -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckK8sHDFSAccess() {
    local principal=$1
    shift 1
# ?Instance,?File
    curl -s -w "checkK8sHDFSAccess %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkK8sHDFSAccess -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkK8sVm() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkK8sVm -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckK8sVm() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkK8sVm %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkK8sVm -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkKeystoneReq() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkKeystoneReq -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckKeystoneReq() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkKeystoneReq %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkKeystoneReq -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkClusterGuard() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkClusterGuard -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckClusterGuard() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkClusterGuard %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkClusterGuard -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkTrustedCluster() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkTrustedCluster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckTrustedCluster() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkTrustedCluster %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkTrustedCluster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkMySQLConnection() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkMySQLConnection -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckMySQLConnection() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkMySQLConnection %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkMySQLConnection -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkCodeQuality() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkCodeQuality -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckCodeQuality() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkCodeQuality %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkCodeQuality -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkDriverFromHDFS() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkDriverFromHDFS -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckDriverFromHDFS() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkDriverFromHDFS %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkDriverFromHDFS -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkAllForSparkEvaluation() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkAllForSparkEvaluation -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckAllForSparkEvaluation() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkAllForSparkEvaluation %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkAllForSparkEvaluation -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkMaster() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkMaster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckMaster() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkMaster %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkMaster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkWorkerFromMaster() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkWorkerFromMaster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckWorkerFromMaster() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkWorkerFromMaster %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkWorkerFromMaster -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkExecutorFromDriver() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkExecutorFromDriver -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckExecutorFromDriver() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkExecutorFromDriver %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkExecutorFromDriver -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkFetch() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkFetch -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckFetch() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkFetch %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkFetch -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkEndorse() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Name,?Value
    curl -XPOST $SAFE_ADDR/checkEndorse -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckEndorse() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Name,?Value
    curl -s -w "checkEndorse %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkEndorse -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\",\"${4}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkBuilder() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkBuilder -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckBuilder() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkBuilder %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkBuilder -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkLaunches() {
# ?Principal,?BearerRef,?Instance,?Image
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
    curl -XPOST $SAFE_ADDR/checkLaunches -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckLaunches() {
    local principal=$1
    shift 1
# ?Instance,?Image
    curl -s -w "checkLaunches %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkLaunches -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkConfig() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -XPOST $SAFE_ADDR/checkConfig -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckConfig() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -s -w "checkConfig %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkConfig -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkBuildsFrom() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Value
    curl -XPOST $SAFE_ADDR/checkBuildsFrom -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckBuildsFrom() {
    local principal=$1
    shift 1
# ?Instance,?Image,?Value
    curl -s -w "checkBuildsFrom %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkBuildsFrom -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkProperty() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance,?Name,?Value
    curl -XPOST $SAFE_ADDR/checkProperty -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckProperty() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -s -w "checkProperty %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkProperty -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkAttester() {  # Note that this is essentially the same as function checkAttesterLocal()
# ?Principal,?BearerRef,?Instance
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
    echo curl -XPOST $SAFE_ADDR/checkAttester -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
    curl -XPOST $SAFE_ADDR/checkAttester -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkAttesterLocal() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    echo curl -XPOST $SAFE_ADDR/checkAttester -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
    curl -XPOST $SAFE_ADDR/checkAttester -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckAttester() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkAttester %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkAttester -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkTrustedCode() {
    local principal=$1
    shift 1
# ?Image, ?Delegator
    curl -XPOST $SAFE_ADDR/checkTrustedCode -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckTrustedCode() {
    local principal=$1
    shift 1
# ?Image, ?Delegator
    curl -s -w "checkTrustedCode %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkTrustedCode -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkTrustedConnections() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkTrustedConnections -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckTrustedConnections() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkTrustedConnections %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkTrustedConnections -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}
        
checkTrustedEndorser() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckTrustedEndorser() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkTrustedEndorser %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkTrustedEndorser -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}
        
checkEndorsed() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkEndorsed -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\", \"${3}\", \"${4}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckEndorsed() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkEndorsed %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkEndorsed -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\", \"${3}\", \"${4}\"], \"auth\":\"${AUTH:-1}\"}"
}
        
debug() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -XPOST $SAFE_ADDR/debug -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measuredebug() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -s -w "debug %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/debug -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

postImagePolicy() {
    local principal=$1
    shift 1

# Deprecated
# ?Instance
#    curl -XPOST $SAFE_ADDR/postImageSpec -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"

# ?policyId, ?imageList
    curl -XPOST $SAFE_ADDR/postImagePolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

# TODO: fix this
measureImagePolicy() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "postImageSpec %{time_total}
" -o postImagePolicy.log -XPOST $SAFE_ADDR/postImagePolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

postPropertyPolicy() {
    local principal=$1
    shift 1

# Deprecated
# ?Instance,?Name,?Value
#    curl -XPOST $SAFE_ADDR/postPropertySpec -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"AUTH\":\"${AUTH:-1}\"}"

    local policyId=$1
    shift 1

    curl -XPOST $SAFE_ADDR/postRequiredPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${policyId}\",\"${1}\"], \"auth\":\"${AUTH:-1}\"}"

    shift 1
    curl -XPOST $SAFE_ADDR/postQualifierPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${policyId}\",\"${1}\"], \"auth\":\"${AUTH:-1}\"}"

    shift 1
    curl -XPOST $SAFE_ADDR/postProhibitedPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${policyId}\",\"${1}\"], \"auth\":\"${AUTH:-1}\"}"

}

# TODO: fix this
measurePropertyPolicy() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -s -w "postPropertySpec %{time_total}
" -o postPropertyPolicy.log -XPOST $SAFE_ADDR/postPropertyPolicy -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkHasConfig() {
# ?Principal,?BearerRef,?Instance,?Name,?Value
    local principal=$1
    shift 1
    local bearer=$1
    shift 1

    curl -XPOST $SAFE_ADDR/checkHasConfig -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckHasConfig() {
    local principal=$1
    shift 1
# ?Instance,?Name,?Value
    curl -s -w "checkHasConfig %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkHasConfig -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\",\"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkPodAttestation() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/checkPodAttestation -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkPodAttestationLocal() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    echo curl -XPOST $SAFE_ADDR/checkPodAttestationLocal -d \' "{ \"bearerRef\": \"$bearer\",\"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}" \'
    curl -XPOST $SAFE_ADDR/checkPodAttestationLocal -d "{ \"bearerRef\": \"$bearer\",\"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}

measureCheckPodAttestation() {
    local principal=$1
    shift 1
# ?Instance
    curl -s -w "checkPodAttestation %{time_total}
" -o debug.log -XPOST $SAFE_ADDR/checkPodAttestation -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\"], \"auth\":\"${AUTH:-1}\"}"
}
        
debugCheck1() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/debugCheck1 -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

debugCheck2() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/debugCheck2 -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

debugCheck3() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/debugCheck3 -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\", \"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}

debugCheck4() {
    local principal=$1
    shift 1
# ?Instance
    curl -XPOST $SAFE_ADDR/debugCheck4 -d "{ \"principal\": \"$principal\", \"methodParams\": [\"${1}\", \"${2}\" ], \"auth\":\"${AUTH:-1}\"}"
}

checkPodByPolicy() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance, ?Policy
    curl -XPOST $SAFE_ADDR/checkPodByPolicy -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkPodAccess() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance, ?Tag                                                                                                                                                         
    curl -XPOST $SAFE_ADDR/checkPodAccess -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkWorker() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance, ?Tag                                                                                                                                                         
    curl -XPOST $SAFE_ADDR/checkWorker -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\"], \"auth\":\"${AUTH:-1}\"}"
}

checkDriverGroup() {
    local principal=$1
    shift 1
    local bearer=$1
    shift 1
# ?Instance, ?Creator, ?PolicyID
                   
    curl -XPOST $SAFE_ADDR/checkDriverGroup -d "{ \"bearerRef\": \"$bearer\", \"principal\": \"$principal\", \"methodParams\": [\"${1}\",\"${2}\", \"${3}\"], \"auth\":\"${AUTH:-1}\"}"
}