#!/bin/bash

postSparkPod() {
  pod=$1
  type=$2
  curl -XPOST $SAFE_ADDR/postInstance --data-binary "@data/req.${pod}_pod.json"
  curl -XPOST $SAFE_ADDR/postInstanceConfigList --data-binary "@data/req.${pod}_global.json"
  curl -XPOST $SAFE_ADDR/postInstanceConfigList --data-binary "@data/req.${pod}_containers.json"
  curl -XPOST $SAFE_ADDR/postInstanceConfigList --data-binary "@data/req.${pod}__spark-init.json"
  if [ "$type" = "driver" ]; then
      curl -XPOST $SAFE_ADDR/postInstanceConfigList --data-binary "@data/req.${pod}__spark-kubernetes-driver.json"
  elif [ "$type" = "worker" ]; then 
      curl -XPOST $SAFE_ADDR/postInstanceConfigList --data-binary "@data/req.${pod}__executor.json"
  else
      echo "Unrecognized Spark pod type: $type"
      exit 1
  fi
}